# Generated by Django 3.2.4 on 2021-06-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=2)),
                ('document', models.BigIntegerField(unique=True)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
